name: checkout workflow
on:
  workflow_dispatch:

jobs:
  checkout-yo:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v3
  echo-yo:
      runs-on: ubuntu-latest
      steps:
      - name: print echo
        run: echo 'run on echo-yo'
      - name: print working directory
        run: pwd
